name: Ejecutar Monitor de Telcos

on:
  schedule:
    - cron: '0 9,15,21 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código del repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Playwright y Navegador
        run: |
          pip install playwright
          playwright install chromium

      - name: Ejecutar el agente
        run: python agente_telco.py
